### ISSUE TITLE
Porting gopherjs js calls to use with vecty

### ISSUE THREAD

**Issue by soypat** [hexops/vecty#295]
Hello there! I am looking to use some [bindings I have been working on](https://github.com/soypat/three) for use with gopherjs. Was wondering how much would it hurt to used them with vecty instead. These are the questions I have:
* Do I have to modify the bindings for use with vecty? How much will it hurt if so? 
* Can I modify them so that they still work with gopherjs?
* What are the downsides to continuing using gopherjs?

This is the binding's initialization procedure: https://github.com/soypat/three/blob/master/main.go

**Comment by slimsag** [comment]
See https://github.com/hexops/vecty/issues/264

From the looks of it, GopherJS recently added a `syscall/js` package compatible with the official Go standard library: https://github.com/gopherjs/gopherjs#whats-new

Pretty sure you just need to start using [`syscall/js`](https://pkg.go.dev/syscall/js) instead of the (pretty much deprecated) `github.com/gopherjs/gopherjs/js` package.

Vecty just uses the official Go stdlib's JS support, it doesn't do anything fancy to support Go compilers that are not compatible with official Go. See https://github.com/hexops/vecty/pull/265 (but again note you probably just need to start using the new package and things likely just work in both gopherjs and vecty then.)

**Comment by soypat** [comment]
Thank you for the quick response! Alright so i'll just migrate to syscall/js!
